language: ruby

env:
  - DB=postgresql

rvm:
  - 2.1.3

addons:
  code_climate:
    repo_token:
      secure: "WIyvPYejilSlf+GTGMnOtKeFz01t667INGuaPguWkVm0nkBIYaedXrdnF2o6Hz/Xbji14Hozylh7oBIumC+37bw5/DQtoPHS8/EJ5zKOrOSGsYOciQRRNIhQkAKmNANqmBkM4Tr2EiWZeRcQKtJFtlBSXJ55RFUML+PON0RljbQ="

before_script:
  - psql -c 'create database oeco_database_test' -U postgres

deploy:
  - provider: heroku
    api_key:
      secure: Frb5UjVgjJqPrtaao4vcQwvRYlKGy2Eg/8r6+ejeX7rSrwwVhZGuKWAv4Qpk8xNu+T4DK2ZEBgzxpfFfw3xhlLfynjrezbqHyFKDEatDEu2KPmUEwpCL/TvQehwqBJmaWCKWSxFAgwl7ODQj0vezna94GjvulQg7eO3rGxZK0Rk=
    app: oeco-staging
    on:
      tags: false
    strategy: git
    run:
      - "rake db:migrate"
      - restart
      - "rake cleanup"
  - provider: heroku
    api_key:
      secure: Frb5UjVgjJqPrtaao4vcQwvRYlKGy2Eg/8r6+ejeX7rSrwwVhZGuKWAv4Qpk8xNu+T4DK2ZEBgzxpfFfw3xhlLfynjrezbqHyFKDEatDEu2KPmUEwpCL/TvQehwqBJmaWCKWSxFAgwl7ODQj0vezna94GjvulQg7eO3rGxZK0Rk=
    app: oeco
    on:
      all_branches: true
      tags: true
    strategy: git
    run:
      - "rake db:migrate"
      - restart
      - "rake cleanup"
