sudo: false
language: ruby
cache: bundler
rvm:
  - 2.1.3
before_script:
  - bin/rake db:migrate RAILS_ENV=test
deploy:
  - provider: heroku
    api_key: $HEROKU_AUTH_TOKEN
    app: oeco-ruby-staging
    on:
      all_branches: true
      tags: false
    strategy: git
    run:
      - rake db:migrate
      - restart
      - rake cleanup
  - provider: heroku
    api_key: $HEROKU_AUTH_TOKEN
    app: oeco-ruby
    on:
      all_branches: true
      tags: true
    strategy: git
    run:
      - rake db:migrate
      - restart
      - rake cleanup
after_deploy: curl -sf -o /dev/null -w '%{http_code}\n' "http://$([ "$TRAVIS_TAG" == "" ] && echo "$OECO_STAGING_USERNAME:$OECO_STAGING_PASSWORD@oeco-ruby-staging" || echo "oeco-ruby").herokuapp.com/" || exit $?
