sudo: false
language: ruby
cache: bundler
rvm:
  - 2.1.3
before_script:
  - bin/rake db:migrate RAILS_ENV=test
deploy:
  - provider: heroku
    api_key:
      secure: Frb5UjVgjJqPrtaao4vcQwvRYlKGy2Eg/8r6+ejeX7rSrwwVhZGuKWAv4Qpk8xNu+T4DK2ZEBgzxpfFfw3xhlLfynjrezbqHyFKDEatDEu2KPmUEwpCL/TvQehwqBJmaWCKWSxFAgwl7ODQj0vezna94GjvulQg7eO3rGxZK0Rk=
    app: oeco-ruby-staging
    on:
      all_branches: true
      tags: false
    strategy: git
    run:
      - rake db:migrate
      - restart
      - rake cleanup
  - provider: heroku
    api_key:
      secure: Frb5UjVgjJqPrtaao4vcQwvRYlKGy2Eg/8r6+ejeX7rSrwwVhZGuKWAv4Qpk8xNu+T4DK2ZEBgzxpfFfw3xhlLfynjrezbqHyFKDEatDEu2KPmUEwpCL/TvQehwqBJmaWCKWSxFAgwl7ODQj0vezna94GjvulQg7eO3rGxZK0Rk=
    app: oeco-ruby
    on:
      all_branches: true
      tags: true
    strategy: git
    run:
      - rake db:migrate
      - restart
      - rake cleanup
after_deploy: curl -sf -o /dev/null -w '%{http_code}\n' "http://$([ "$TRAVIS_TAG" == "" ] && echo "$OECO_STAGING_USERNAME:$OECO_STAGING_PASSWORD@oeco-staging" || echo "oeco").herokuapp.com/" || exit $?
