sudo: false
language: ruby
cache: bundler
env:
  global:
  - DB=postgresql
rvm:
- 2.1.3
addons:
  code_climate:
    repo_token:
      secure: K0uONI4vqqle7wgOKkyr1JewCdokMWYMYTP7ZEFK8vsWcxry1wM2M+y0KVYbvGwteXfGB8VlZNaf2bBrVDaebCMLBmSNdChdU97Xtj2RSgcPWIi8hbeSUFQbfmHNXcCcsH5Qw0DByV/stz/2w+uH9wciTPnpl9kyXpqhRqyT2Kg=
before_script:
- psql -c 'create database oeco_database_test' -U postgres
deploy:
- provider: heroku
  api_key:
    secure: Frb5UjVgjJqPrtaao4vcQwvRYlKGy2Eg/8r6+ejeX7rSrwwVhZGuKWAv4Qpk8xNu+T4DK2ZEBgzxpfFfw3xhlLfynjrezbqHyFKDEatDEu2KPmUEwpCL/TvQehwqBJmaWCKWSxFAgwl7ODQj0vezna94GjvulQg7eO3rGxZK0Rk=
  app: oeco-staging
  on:
    all_branches: true
    tags: false
  strategy: git
  run:
  - rake db:migrate
  - restart
  - rake cleanup
- provider: heroku
  api_key:
    secure: Frb5UjVgjJqPrtaao4vcQwvRYlKGy2Eg/8r6+ejeX7rSrwwVhZGuKWAv4Qpk8xNu+T4DK2ZEBgzxpfFfw3xhlLfynjrezbqHyFKDEatDEu2KPmUEwpCL/TvQehwqBJmaWCKWSxFAgwl7ODQj0vezna94GjvulQg7eO3rGxZK0Rk=
  app: oeco
  on:
    all_branches: true
    tags: true
  strategy: git
  run:
  - rake db:migrate
  - restart
  - rake cleanup
after_deploy: curl -sf -o /dev/null -w '%{http_code}\n' "http://$([ "$TRAVIS_TAG" == "" ] && echo "$OECO_STAGING_USERNAME:$OECO_STAGING_PASSWORD@oeco-staging" || echo "oeco").herokuapp.com/" || exit $?
