# Automatically generated by Scaffold_htm Generator.
class CreateProjectsProperties < ActiveRecord::Migration
  def change
    create_table :projects_properties do |t|
      t.integer :project_id
      t.integer :property_id
      t.timestamps
    end
    add_index :projects_properties, :project_id
    add_index :projects_properties, :property_id
  end
end
