# Automatically generated by Scaffold_htm Generator.
class CreateCategoriesProjects < ActiveRecord::Migration
  def change
    create_table :categories_projects do |t|
      t.integer :category_id
      t.integer :project_id
      t.timestamps
    end
    add_index :categories_projects, :category_id
    add_index :categories_projects, :project_id
  end
end
